app/routes/mahasiswa.py
import os
from flask import Blueprint, Flask, jsonify, render_template, send_from_directory, session, redirect, url_for, request
import sqlite3
from werkzeug.utils import secure_filename

app = Flask(__name__)
mahasiswa_bp = Blueprint('mahasiswa', __name__)

UPLOAD_FOLDER = os.path.join('uploads', 'bap')

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
ALLOWED_EXTENSIONS = {'pdf'}
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# Fungsi untuk membuat penamaan file tetap sama
def generate_filename(id_sidang):
    return f'bap_{id_sidang}.pdf'


def get_db_connection():
    conn = sqlite3.connect('database/database.db') 
    conn.row_factory = sqlite3.Row 
    return conn

@mahasiswa_bp.before_request
def require_login():
    allowed_routes = ['login', 'static']
    if 'email' not in session and request.endpoint not in allowed_routes:
        return redirect(url_for('login'))
    
@mahasiswa_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login'))

@mahasiswa_bp.route('/')
def dashboard():
    return redirect(url_for('home'))

@mahasiswa_bp.route('/home')
def home():
    nama = session.get('nama', None)
    role = session.get('role', None)
    return render_template('mahasiswa/mahasiswa-home.html', nama = nama, role=role)

@mahasiswa_bp.route('/info')
def info():
    nama = session.get('nama', None)
    npm = session.get('id', None)
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("select * from InfoSidang where npm_mahasiswa = ? and status = ?", (npm, 'active'))
    info_sidang = cursor.fetchone()
    print(info_sidang)
    return render_template('mahasiswa/mahasiswa-info.html', nama = nama, info = info_sidang)

@mahasiswa_bp.route('/catatan')
def catatan():
    nama = session.get('nama', None)
    role = session.get('role', None)
    npm = session.get('id', None)
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("select catatan from InfoSidang where npm_mahasiswa = ? and status = ?", (npm, 'active'))
    catatan = cursor.fetchall()
    return render_template('mahasiswa/mahasiswa-catatan.html', nama = nama, catatan=catatan)

@mahasiswa_bp.route('/nilai')
def nilai():
    conn = get_db_connection()  
    npm = session['id']
    print("npm kamu adalah: " + npm)
    nama = session.get('nama', None)
    role = session.get('role', None)
    
    # bobots = conn.execute('SELECT * FROM Bobot_PerTahun_Ajaran').fetchall()
    bobots = conn.execute('''
        SELECT DISTINCT 
            b.ID_Tahun_Ajaran, 
            (2018 + b.ID_Tahun_Ajaran) || '/' || (2019 + b.ID_Tahun_Ajaran) AS tahun_ajaran
        FROM Bobot_PerTahun_Ajaran b
        JOIN Sidang s ON b.ID_Tahun_Ajaran = s.ID_Tahun_Ajaran
        WHERE s.npm = ?
    ''', (npm,)).fetchall()

    
    # # Ambil informasi sidang
    # sidang_info = conn.execute('''
    #     SELECT s.ID_Sidang, s.tempat_sidang, s.tanggal_sidang, s.waktu_mulai, s.waktu_selesai, s.catatan
    #     FROM InfoSidang s
    #     WHERE s.npm_mahasiswa = ? AND s.status = ?
    # ''', (npm, 'active')).fetchone()
    
    
    sidang_info = conn.execute('''
        SELECT s.ID_Sidang, s.tempat_sidang, s.tanggal_sidang, s.waktu_mulai, s.waktu_selesai, s.catatan
        FROM Sidang s
        WHERE s.npm = ?
        LIMIT 1
    ''', (npm,)).fetchone()


    tahun_ajaran = request.args.get('tahun_ajaran', None)
    print(tahun_ajaran)
    if tahun_ajaran:
        # Filter berdasarkan tahun ajaran jika dipilih
        # Ambil informasi sidang
        sidang_info = conn.execute('''
            SELECT s.ID_Sidang, s.tempat_sidang, s.tanggal_sidang, s.waktu_mulai, s.waktu_selesai, s.catatan
            FROM Sidang s
            WHERE s.ID_Tahun_Ajaran = ? AND s.npm = ?
        ''', (tahun_ajaran, npm)).fetchone()
        
    print(sidang_info)
        
    # Query gabungan untuk menghitung nilai total sidang berdasarkan bobot
    # Query gabungan untuk menghitung nilai total sidang berdasarkan bobot
    nilai_detail_query = '''
        SELECT 
            np1.tata_tulis AS nilai_tata_tulis_penguji1,
            np1.kelengkapan_materi AS nilai_kelengkapan_materi_penguji1,
            np1.pencapaian_tujuan AS nilai_pencapaian_tujuan_penguji1,
            np1.penguasaan_materi AS nilai_penguasaan_materi_penguji1,
            np1.presentasi AS nilai_presentasi_penguji1,
            np2.tata_tulis AS nilai_tata_tulis_penguji2,
            np2.kelengkapan_materi AS nilai_kelengkapan_materi_penguji2,
            np2.pencapaian_tujuan AS nilai_pencapaian_tujuan_penguji2,
            np2.penguasaan_materi AS nilai_penguasaan_materi_penguji2,
            np2.presentasi AS nilai_presentasi_penguji2,
            
            nb.tata_tulis AS nilai_tata_tulis_pembimbing,
            nb.kelengkapan_materi AS nilai_kelengkapan_materi_pembimbing,
            nb.proses_bimbingan  AS nilai_proses_bimbingan_pembimbing,
            nb.penguasaan_materi  AS nilai_penguasaan_materi_pembimbing,
            
            nk.nilai AS nilai_koordinator,
            
            (
                (((np1.tata_tulis + np2.tata_tulis) * b.tata_tulis_penguji) +
                ((np1.kelengkapan_materi + np2.kelengkapan_materi) * b.kelengkapan_materi_penguji) +
                ((np1.pencapaian_tujuan + np2.pencapaian_tujuan) * b.pencapaian_tujuan_penguji) +
                ((np1.penguasaan_materi + np2.penguasaan_materi) * b.penguasaan_materi_penguji) +
                ((np1.presentasi + np2.presentasi) * b.presentasi_penguji)) * (b.bobot_penguji/2) +

                (nb.tata_tulis * b.tata_tulis_pembimbing + 
                nb.kelengkapan_materi * b.kelengkapan_materi_pembimbing + 
                nb.proses_bimbingan * b.proses_bimbingan_pembimbing + 
                nb.penguasaan_materi * b.penguasaan_materi_pembimbing) * b.bobot_pembimbing +

                (nk.nilai * b.bobot_koordinator)
            ) AS total_nilai
            
        FROM Sidang s
        JOIN Nilai_Penguji np1 ON np1.ID_Sidang = s.ID_Sidang
        JOIN Nilai_Penguji np2 ON np2.ID_Sidang = s.ID_Sidang AND np2.ID_Nilai_Penguji != np1.ID_Nilai_Penguji
        JOIN Nilai_Pembimbing nb ON nb.ID_Sidang = s.ID_Sidang
        JOIN Nilai_Koordinator nk ON nk.id_sidang = s.ID_Sidang
        JOIN Bobot_PerTahun_Ajaran b ON s.ID_Tahun_Ajaran = b.ID_Tahun_Ajaran
        WHERE s.npm = ?
    '''

    # Jika tahun_ajaran diberikan, tambahkan kondisi filter untuk tahun_ajaran
    if tahun_ajaran:
        nilai_detail_query += ' AND s.ID_Tahun_Ajaran = ?'

    # Menjalankan query dengan parameter
    nilai_detail = conn.execute(nilai_detail_query, (npm, tahun_ajaran) if tahun_ajaran else (npm,)).fetchone()
    conn.close()
    print(nilai_detail)
    
    if not sidang_info or not nilai_detail:
        return f"Tidak ada data nilai sidang untuk mahasiswa dengan NPM '{npm}'", 404
    
    # Format data menjadi dictionary
    sidang_dict = dict(sidang_info) if sidang_info else {}
    nilai_dict = dict(nilai_detail) if nilai_detail else {}

    # Cek apakah pengguna meminta JSON
    if request.args.get('format') == 'json':
        return jsonify({
            'sidang': sidang_dict,
            'nilai_detail': nilai_dict
        })

    print(nilai_detail)
    print("tes")

    # Jika tidak, render template HTML
    return render_template(
        'mahasiswa/mahasiswa-nilai.html', 
        nama=nama, 
        sidang=sidang_info, 
        nilai_detail=nilai_detail,
        bobots=bobots
    )

    
    # return render_template('mahasiswa/mahasiswa-nilai.html', nama = nama, sidang=sidang_info, nilai_detail=nilai_detail)

@mahasiswa_bp.route('/uploads/bap/<filename>')
def serve_bap_file(filename):
    return send_from_directory('uploads/bap', filename)

@mahasiswa_bp.route('/bap', methods=['GET'])
def bap():
    nama = session.get('nama', None)
    npm = session.get('id', None)
    conn = get_db_connection()

    # Ambil data BAP terkait dengan mahasiswa berdasarkan npm (melalui sidang yang terkait)
    cursor = conn.cursor()
    cursor.execute('''
        SELECT * FROM BAP
        WHERE idSidang IN (SELECT ID_Sidang FROM Sidang WHERE npm = ? and status = ?)
    ''', (npm, 'active'))
    bap_data = cursor.fetchone()

    conn.close()
    
    # Jika BAP ditemukan, tampilkan data, jika tidak, beri notifikasi
    if not bap_data:
        return "BAP belum tersedia", 404

    print(bap_data['file_path'])
    return render_template('mahasiswa/mahasiswa-bap.html', nama=nama, bap_data=bap_data)


@mahasiswa_bp.route('/bap/unduh', methods=['POST'])
def unduh_bap():
    npm = session.get('id', None)
    if not npm:
        return "Anda tidak memiliki akses", 403

    conn = get_db_connection()

    # Ambil file_path BAP berdasarkan npm (melalui sidang yang terkait)
    cursor = conn.cursor()
    cursor.execute('''
        SELECT file_path FROM BAP
        WHERE idSidang IN (SELECT ID_Sidang FROM Sidang WHERE npm = ? and status = ?)
    ''', (npm, 'active'))
    bap_data = cursor.fetchone()

    conn.close()

    # Jika BAP ditemukan, unduh file
    if bap_data and bap_data['file_path']:
        file_path = bap_data['file_path']

        # Pastikan file_path valid
        if not os.path.isfile(file_path):
            return "File tidak ditemukan di server", 404

        # Ekstrak direktori dan nama file
        directory = os.path.dirname(file_path)
        filename = os.path.basename(file_path)

        # Kirim file ke pengguna
        return send_from_directory(directory=directory, path=filename, as_attachment=True)

    return "BAP tidak ditemukan", 404



@mahasiswa_bp.route('/bap/uploads', methods=['GET','POST'])
def upload_bap():
    npm = session.get('id', None)
    file = request.files.get('bap_file')

    if not file:
        return "Tidak ada file yang diunggah", 400

    # Cek apakah ekstensi file diizinkan
    if not allowed_file(file.filename):

templates/mahasiswa/mahasiswa-bap.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sidang Akhir</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mahasiswa/mahasiswa-bap.css') }}">
  <script>
      document.addEventListener('DOMContentLoaded', function () {
              const today = new Date();
              const currentMonth = today.getMonth(); // Desember = 11
              const currentYear = today.getFullYear();
              const currentDate = today.getDate();
      
              // Pastikan bulan dan tahun adalah Desember 2024
              if (currentMonth === 11 && currentYear === 2024) {
                  // Cari elemen <td> dengan data-day yang sesuai
                  const todayCell = document.querySelector(`td[data-day='${currentDate}']`);
                  if (todayCell) {
                      todayCell.style.backgroundColor = '#2d89ef';
                      todayCell.style.borderRadius = '50%';
                      todayCell.style.fontWeight = 'bold';
                  }
              }
            });
  </script>
</head>
<body>
  <div class="container">
    <!-- Sidebar -->
    {% include 'mahasiswa/fragment/sidebar.html' %}

    <!-- Main Content -->
    <div class="main-content">
        <div class="content-header">
            <h2>BAP (Berita Acara Sidang)</h2>
        </div>
        <div class="content-body">
            <!-- Preview PDF -->
            {% if bap_data.file_path %}
            <div id="pdf-preview">
                <h4>Preview BAP:</h4>
                <embed 
                    id="pdf-embed" 
                    type="application/pdf" 
                    src="{{ url_for('mahasiswa.serve_bap_file', filename=bap_data['file_path'].split('/')[-1]) }}" 
                    width="100%" 
                    height="550px">
            </div>
            {% else %}
            <p style="color: red;">BAP belum tersedia.</p>
            {% endif %}

            <div id="buttons">
              <form action="{{ url_for('mahasiswa.upload_bap') }}" method="POST" enctype="multipart/form-data">
                <input type="file" name="bap_file" required>
                <button type="submit" class="btn-upload" {% if bap_data.status_pembimbing == 'belum' %}disabled{% endif %}>Upload</button>
              </form>
            
              <form action="{{ url_for('mahasiswa.unduh_bap') }}" method="POST">
                <button type="submit" class="btn-unduh">Unduh</button>
              </form>
            
            </div>
        </div>
    </div>

    <!-- Rightbar Section -->
    {% include 'mahasiswa/fragment/rightbar.html' %}
  </div>
</body>
</html>

templates/mahasiswa/mahasiswa-catatan.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Catatan Sidang</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mahasiswa/mahasiswa-catatan.css') }}">
  <script>
           document.addEventListener('DOMContentLoaded', function () {
              const today = new Date();
              const currentMonth = today.getMonth(); // Desember = 11
              const currentYear = today.getFullYear();
              const currentDate = today.getDate();
      
              // Pastikan bulan dan tahun adalah Desember 2024
              if (currentMonth === 11 && currentYear === 2024) {
                  // Cari elemen <td> dengan data-day yang sesuai
                  const todayCell = document.querySelector(`td[data-day='${currentDate}']`);
                  if (todayCell) {
                      todayCell.style.backgroundColor = '#2d89ef';
                      todayCell.style.borderRadius = '50%';
                      todayCell.style.fontWeight = 'bold';
                  }
              }
            });
  </script>
</head>
<body>
  <div class="container">
    <!-- Sidebar -->
    {% include 'mahasiswa/fragment/sidebar.html' %}

    <!-- Main Content -->
    <main class="content">
      <div class="content-header">
        Catatan Sidang
      </div>
      <br>
      <div class="notes">
        {% if catatan %}
          {% for note in catatan %}
            <p><strong>Catatan:</strong></p>
            <ul>
              <li>{{ note.catatan }}</li>
            </ul>
          {% endfor %}
        {% else %}
          <p>Belum ada catatan untuk sidang ini.</p>
        {% endif %}
      </div>
    </main>

    <!-- Rightbar Section -->
    {% include 'mahasiswa/fragment/rightbar.html' %}
  </div>
</body>
</html>

templates/mahasiswa/mahasiswa-home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Catatan Sidang</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mahasiswa/mahasiswa-home.css') }}">
  <script>
            document.addEventListener('DOMContentLoaded', function () {
              const today = new Date();
              const currentMonth = today.getMonth(); // Desember = 11
              const currentYear = today.getFullYear();
              const currentDate = today.getDate();
      
              // Pastikan bulan dan tahun adalah Desember 2024
              if (currentMonth === 11 && currentYear === 2024) {
                  // Cari elemen <td> dengan data-day yang sesuai
                  const todayCell = document.querySelector(`td[data-day='${currentDate}']`);
                  if (todayCell) {
                      todayCell.style.backgroundColor = '#2d89ef';
                      todayCell.style.borderRadius = '50%';
                      todayCell.style.fontWeight = 'bold';
                  }
              }
            });
  </script>
</head>
<body>
  <div class="container">
    <!-- Sidebar -->
    {% include 'mahasiswa/fragment/sidebar.html' %}

    <!-- Main Content -->
    <main class="content">
        <div class="welcome-box">
          <h2>Welcome back, {{role}}!</h2>
          <p>1 Petrus 5:7</p>
          <p>"Serahkanlah segala kekuatiranmu kepadaNya, sebab Ia yang memelihara kamu."</p>
        </div>
        <br>
        <hr>
        <br>
        <div class="menu-grid">
          <a href="info" class="menu-item">Info Sidang</a>
          <a href="bap" class="menu-item">BAP</a>
          <a href="nilai" class="menu-item">Nilai</a>
          <a href="catatan" class="menu-item">Catatan Sidang</a>
        </div>
    </main>

    <!-- Rightbar Section -->
    {% include 'mahasiswa/fragment/rightbar.html' %}
  </div>
</body>
</html>

templates/mahasiswa/mahasiswa-info.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Catatan Sidang</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mahasiswa/mahasiswa-info.css') }}">
  <script>
           document.addEventListener('DOMContentLoaded', function () {
              const today = new Date();
              const currentMonth = today.getMonth(); // Desember = 11
              const currentYear = today.getFullYear();
              const currentDate = today.getDate();
      
              // Pastikan bulan dan tahun adalah Desember 2024
              if (currentMonth === 11 && currentYear === 2024) {
                  // Cari elemen <td> dengan data-day yang sesuai
                  const todayCell = document.querySelector(`td[data-day='${currentDate}']`);
                  if (todayCell) {
                      todayCell.style.backgroundColor = '#2d89ef';
                      todayCell.style.borderRadius = '50%';
                      todayCell.style.fontWeight = 'bold';
                  }
              }
            });
  </script>
</head>
<body>
  <div class="container">
    <!-- Sidebar -->
    {% include 'mahasiswa/fragment/sidebar.html' %}

    <!-- Main Content -->
    <div class="content">
        <div class="welcome-box">
          Info Sidang
        </div>
        <br>
        <div class="info-details">
          <table class="info-table">
            <tr>
                <td>Tanggal</td>
                <td>:</td>
                <td>{{info.tanggal_sidang}}</td>
            </tr>
            <tr>
                <td>Waktu</td>
                <td>:</td>
                <td>{{info.waktu_mulai}} s/d {{info.waktu_selesai}}</td>
            </tr>
            <tr>
                <td>Ruangan</td>
                <td>:</td>
                <td>{{info.tempat_sidang}}</td>
            </tr>
            <tr>
                <td>Pembimbing</td>
                <td>:</td>
                <td>{{info.nama_pembimbing}}</td>
            </tr>
            <tr>
                <td>Penguji</td>
                <td>:</td>
                <td>{{info.nama_penguji}}</td>
            </tr>
        </table>
        </div>
    </div>

    <!-- Rightbar Section -->
    {% include 'mahasiswa/fragment/rightbar.html' %}
  </div>
</body>
</html>

templates/mahasiswa/mahasiswa-nilai.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sidang Akhir</title>
  <link rel="stylesheet" href="../../static/css/mahasiswa/mahasiswa-nilai.css">
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const selectElement = document.getElementById('tahunAjaranSelect');
      const tahunAjaranId = new URLSearchParams(window.location.search).get('tahun_ajaran');
      if (tahunAjaranId) {
        selectElement.value = tahunAjaranId;
      }
      selectElement.addEventListener('change', function() {
        const tahunAjaranId = this.value;
        console.log("Tahun Ajaran yang dipilih:", tahunAjaranId);
        window.location.href = `?tahun_ajaran=${tahunAjaranId}`;
      });
    });
    document.addEventListener('DOMContentLoaded', function () {
              const today = new Date();
              const currentMonth = today.getMonth(); // Desember = 11
              const currentYear = today.getFullYear();
              const currentDate = today.getDate();
      
              // Pastikan bulan dan tahun adalah Desember 2024
              if (currentMonth === 11 && currentYear === 2024) {
                  // Cari elemen <td> dengan data-day yang sesuai
                  const todayCell = document.querySelector(`td[data-day='${currentDate}']`);
                  if (todayCell) {
                      todayCell.style.backgroundColor = '#2d89ef';
                      todayCell.style.borderRadius = '50%';
                      todayCell.style.fontWeight = 'bold';
                  }
              }
            });
  </script>
</head>
<body>
  <div class="container">
    {% include 'mahasiswa/fragment/sidebar.html' %}

    <main class="content">
      <header class="header">
        <div class="welcome-box">Nilai Sidang</div>
        <select id="tahunAjaranSelect" name="tahun_ajaran">
          {% for tahun in bobots %}
            <option value="{{ tahun.ID_Tahun_Ajaran }}" 
              {% if tahun_ajaran == tahun.ID_Tahun_Ajaran %}selected{% endif %}>
              {{ tahun.tahun_ajaran }}
            </option>
          {% endfor %}
        </select>
      </header>
      
      {% if sidang and nilai_detail %}
        <table>
          <thead>
            <tr>
              <th>No.</th>
              <th>Detail Nilai</th>
              <th>Nilai Penguji 1</th>
              <th>Nilai Penguji 2</th>
              <th>Nilai Pembimbing</th>
              <th>Nilai Koordinator</th>
              <th>Angka Akhir</th>
              <th>Nilai Akhir</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Tata Tulis</td>
              <td>{{ nilai_detail.nilai_tata_tulis_penguji1 }}</td>
              <td>{{ nilai_detail.nilai_tata_tulis_penguji2 }}</td>
              <td>{{ nilai_detail.nilai_tata_tulis_pembimbing }}</td>
              <td rowspan="6">{{ nilai_detail.nilai_koordinator }}</td>
              <td rowspan="6">
                {% if nilai_detail.total_nilai is not none %}
                  {{ nilai_detail.total_nilai | round(2) }}
                {% else %}
                  Tidak Ada Nilai
                {% endif %}
              </td>
              <td rowspan="6">
                {% if nilai_detail.total_nilai >= 80 %}
                  A
                {% elif 77 <= nilai_detail.total_nilai <= 79 %}
                  A-
                {% elif 73 <= nilai_detail.total_nilai <= 76 %}
                  B+
                {% elif 70 <= nilai_detail.total_nilai <= 72 %}
                  B
                {% elif 67 <= nilai_detail.total_nilai <= 69 %}
                  B-
                {% elif 63 <= nilai_detail.total_nilai <= 66 %}
                  C+
                {% elif 60 <= nilai_detail.total_nilai <= 62 %}
                  C
                {% elif 50 <= nilai_detail.total_nilai <= 59 %}
                  D
                {% else %}
                  E
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>2</td>
              <td>Kelengkapan Materi</td>
              <td>{{ nilai_detail.nilai_kelengkapan_materi_penguji1 }}</td>
              <td>{{ nilai_detail.nilai_kelengkapan_materi_penguji2 }}</td>
              <td>{{ nilai_detail.nilai_kelengkapan_materi_pembimbing }}</td>
            </tr>
            <tr>
              <td>3</td>
              <td>Pencapaian Tujuan</td>
              <td>{{ nilai_detail.nilai_pencapaian_tujuan_penguji1 }}</td>
              <td>{{ nilai_detail.nilai_pencapaian_tujuan_penguji2 }}</td>
              <td>{{ nilai_detail.nilai_proses_bimbingan_pembimbing }}</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Penguasaan Materi</td>
              <td>{{ nilai_detail.nilai_penguasaan_materi_penguji1 }}</td>
              <td>{{ nilai_detail.nilai_penguasaan_materi_penguji2 }}</td>
              <td>{{ nilai_detail.nilai_penguasaan_materi_pembimbing }}</td>
            </tr>
            <tr>
              <td>5</td>
              <td>Presentasi</td>
              <td>{{ nilai_detail.nilai_presentasi_penguji1 }}</td>
              <td>{{ nilai_detail.nilai_presentasi_penguji2 }}</td>
              <td></td>
            </tr>
          </tbody>
        </table>
      {% else %}
        <p>Tidak ada data sidang atau nilai ditemukan.</p>
      {% endif %}
    </main>

    {% include 'mahasiswa/fragment/rightbar.html' %}
  </div>
</body>
</html>